name: CI Hook for robotframework-ghareports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install  . '.[dev]'
    - name: Run format check
      run: |
        inv formatcheck
    - name: run ruff
      run: |
        inv ruff
    - name: Tests
      run: |
        inv test
    - name: Run example tests
      run: |
        inv exampleci
