name: CI Hook for robotframework-ghareports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.11, 3.12, 3.13, 3.14]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install  . '.[dev]'
    - name: Run format check
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        inv formatcheck
    - name: run ruff
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        inv ruff
    - name: Tests
      run: |
        inv test
    - name: Run example tests
      run: |
        inv examplecicli
